apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "harbor.fullname" . }}-adminserver"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: adminserver
data:
  DATABASE_TYPE: "postgresql"
  POSTGRESQL_HOST: "{{ template "harbor.database.host" . }}"
  POSTGRESQL_PORT: "{{ template "harbor.database.port" . }}"
  POSTGRESQL_USERNAME: "{{ template "harbor.database.username" . }}"
  POSTGRESQL_DATABASE: "{{ template "harbor.database.coreDatabase" . }}"
  POSTGRESQL_SSLMODE: "{{ template "harbor.database.sslmode" . }}"
  EXT_ENDPOINT: "{{ .Values.externalURL }}"
  CORE_URL: "http://{{ template "harbor.core" . }}"
  JOBSERVICE_URL: "http://{{ template "harbor.fullname" . }}-jobservice"
  REGISTRY_URL: "http://{{ template "harbor.fullname" . }}-registry:5000"
  TOKEN_SERVICE_URL: "http://{{ template "harbor.core" . }}/service/token"
  WITH_NOTARY: "{{ .Values.notary.enabled }}"
  NOTARY_URL: "http://{{ template "harbor.notaryServiceName" . }}:4443"
  LOG_LEVEL: "info"
  IMAGE_STORE_PATH: "/" # This is a temporary hack.
  CFG_EXPIRATION: "5"
  GODEBUG: "netdns=cgo"
  ADMIRAL_URL: "NA"
  RESET: "false"
  WITH_CLAIR: "{{ .Values.clair.enabled }}"
  CLAIR_DB_HOST: "{{ template "harbor.database.host" . }}"
  CLAIR_DB_PORT: "{{ template "harbor.database.port" . }}"
  CLAIR_DB_USERNAME: "{{ template "harbor.database.username" . }}"
  CLAIR_DB: "{{ template "harbor.database.clairDatabase" . }}"
  CLAIR_URL: "http://{{ template "harbor.fullname" . }}-clair:6060"
  CLAIR_DB_SSLMODE: "{{ template "harbor.database.sslmode" . }}"
  UAA_ENDPOINT: ""
  UAA_CLIENTID: ""
  UAA_CLIENTSECRET: ""
  UAA_VERIFY_CERT: "True"
  REGISTRY_STORAGE_PROVIDER_NAME: "{{ .Values.storage.type }}"
  WITH_CHARTMUSEUM: "{{ .Values.chartmuseum.enabled }}"
  CHART_REPOSITORY_URL: "http://{{ template "harbor.fullname" . }}-chartmuseum"
  # The following properties have no default value in Harbor core if not 
  # set via env. They should be removed after the refactoring:
  # AUTH_MODE, SELF_REGISTRATION, PROJECT_CREATION_RESTRICTION 
  AUTH_MODE: "{{ .Values.auth.mode }}"
  SELF_REGISTRATION: "{{ .Values.auth.self_registration }}"
  PROJECT_CREATION_RESTRICTION: "everyone"
  TOKEN_EXPIRATION: "30"
{{ if eq .Values.auth.mode "ldap_auth" }}
  LDAP_URL: "{{ .Values.auth.ldap.url }}"
  LDAP_SEARCH_DN: "{{ .Values.auth.ldap.search_dn }}"
  LDAP_SEARCH_PWD: "{{ .Values.auth.ldap.search_password }}"
  LDAP_BASE_DN: "{{ .Values.auth.ldap.base_dn }}"
  LDAP_FILTER: "{{ .Values.auth.ldap.filter }}"
  LDAP_UID: "{{ .Values.auth.ldap.user_uid }}"
  LDAP_SCOPE: "{{ .Values.auth.ldap.search_scope }}"
  LDAP_TIMEOUT: "{{ .Values.auth.ldap.timeout }}"
{{ end }}
{{ if .Values.email.enabled }}
  EMAIL_HOST: "{{ .Values.email.host }}"
  EMAIL_FROM: "{{ .Values.email.from }}"
  EMAIL_IDENTITY: "{{ .Values.email.identity }}"
  EMAIL_PORT: "{{ .Values.email.port }}"
  EMAIL_USR: "{{ .Values.email.user }}"
  EMAIL_PWD: "{{ .Values.email.password }}"
  EMAIL_SSL: "{{ .Values.email.ssl_enabled }}"
{{ end }}
